#!/bin/bash

echo "enter marks"
read marks

if [[ $marks -gt 90 ]]; then
	echo "distinction"

elif [[ $marks -ge 75 && $marks -le 90 ]]; then
	echo "first class"

elif [[ $marks -ge 60 && $marks -lt 75 ]]; then
	echo "second"

elif [[ $marks -ge 35 && $marks -lt 60 ]]; then
	echo "pass"
else
	echo "fail"
fi


